// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tams.Api.Infrastructure.Data;

#nullable disable

namespace Tams.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TamsDbContext))]
    [Migration("20260602124806_AddAssetTypesAndVariants")]
    partial class AddAssetTypesAndVariants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tams.Api.Domain.Entities.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanBeAssignedToCourse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("can_be_assigned_to_course");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon");

                    b.Property<string>("IdentifierPolicy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identifier_policy");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsReturnable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_returnable");

                    b.Property<int>("ManagedByDepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("managed_by_department_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<bool>("ShowInCalendar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("show_in_calendar");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ManagedByDepartmentId");

                    b.ToTable("asset_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanBeAssignedToCourse = true,
                            Code = "CARD",
                            Color = "#0d6efd",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "NFC card managed by TCO.",
                            Icon = "credit-card",
                            IdentifierPolicy = "Rfid",
                            IsActive = true,
                            IsReturnable = true,
                            ManagedByDepartmentId = 1,
                            Name = "Card",
                            ShowInCalendar = true,
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 2,
                            CanBeAssignedToCourse = true,
                            Code = "LAPTOP",
                            Color = "#198754",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laptop managed by ITC Support.",
                            Icon = "laptop",
                            IdentifierPolicy = "Barcode",
                            IsActive = true,
                            IsReturnable = true,
                            ManagedByDepartmentId = 2,
                            Name = "Laptop",
                            ShowInCalendar = true,
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 3,
                            CanBeAssignedToCourse = true,
                            Code = "USB",
                            Color = "#6f42c1",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "USB device managed by ITC Support.",
                            Icon = "usb",
                            IdentifierPolicy = "Barcode",
                            IsActive = true,
                            IsReturnable = true,
                            ManagedByDepartmentId = 2,
                            Name = "USB",
                            ShowInCalendar = true,
                            SortOrder = 30
                        });
                });

            modelBuilder.Entity("Tams.Api.Domain.Entities.AssetVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_type_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId", "Code")
                        .IsUnique();

                    b.ToTable("asset_variants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetTypeId = 1,
                            Code = "VENDING",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cards physically assigned to vending use.",
                            IsActive = true,
                            Name = "Vending",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 2,
                            AssetTypeId = 1,
                            Code = "CANTEEN",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cards physically assigned to canteen use.",
                            IsActive = true,
                            Name = "Canteen",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 3,
                            AssetTypeId = 1,
                            Code = "INSTRUCTOR",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cards physically assigned to instructors.",
                            IsActive = true,
                            Name = "Instructor",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = 4,
                            AssetTypeId = 1,
                            Code = "GUEST",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cards physically assigned to guests.",
                            IsActive = true,
                            Name = "Guest",
                            SortOrder = 40
                        },
                        new
                        {
                            Id = 5,
                            AssetTypeId = 2,
                            Code = "G8",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laptop model G8.",
                            IsActive = true,
                            Name = "G8",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 6,
                            AssetTypeId = 2,
                            Code = "G10",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laptop model G10.",
                            IsActive = true,
                            Name = "G10",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 7,
                            AssetTypeId = 2,
                            Code = "G11",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laptop model G11.",
                            IsActive = true,
                            Name = "G11",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = 8,
                            AssetTypeId = 3,
                            Code = "STANDARD",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Standard USB device.",
                            IsActive = true,
                            Name = "Standard",
                            SortOrder = 10
                        });
                });

            modelBuilder.Entity("Tams.Api.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "TCO",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "TCO"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ITC",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ITC Support"
                        });
                });

            modelBuilder.Entity("Tams.Api.Domain.Entities.AssetType", b =>
                {
                    b.HasOne("Tams.Api.Domain.Entities.Department", "ManagedByDepartment")
                        .WithMany()
                        .HasForeignKey("ManagedByDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ManagedByDepartment");
                });

            modelBuilder.Entity("Tams.Api.Domain.Entities.AssetVariant", b =>
                {
                    b.HasOne("Tams.Api.Domain.Entities.AssetType", "AssetType")
                        .WithMany("Variants")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetType");
                });

            modelBuilder.Entity("Tams.Api.Domain.Entities.AssetType", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
